version: v0.3
listeners:
- name: http-8899
  address: 0.0.0.0
  port: 8899
  timeout: 300s
setup:
  mode: true
  state: bootstrap
  created_by: vllm-sr serve
  created_at: '2026-07-06T09:47:23.671555+00:00'
